# Config file for Elastic Beanstalk (EB)
# Major edits to modify/ verify before deployment:
## environment name
### 1 environment
### 2 environment-defaults
## application_name
## region
### 1 default_platform - check arn for region
### 2 default_region

---
branch-defaults:
  default:
    environment: $EB_ENV_NAME
global:
  application_name: $EB_APP_NAME
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:$EB_REGION_CODE::platform/Docker
    running on 64bit Amazon Linux/2.12.8
  default_region: $EB_REGION_CODE
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  # Do not include profile value here.
  # It is taken through CircleCI 2.0's environment variable.
  workspace_type: Application
